version: '3'

services:

  pretix:
    image: pretix-with-plugins:latest        # this is the image you built with the Dockerfile!
    container_name: pretix_app
    restart: always 
    depends_on:
      - db
      - redis
    volumes:
      - /mnt/docker/pretix/data:/data         # edit the path, if needed.
      - /mnt/docker/pretix/conf:/etc/pretix   # edit the path, if needed.
    ports:
      - "55580:80"                            # edit the port, if needed. In this case, point to 55580 with your reverse proxy! 
    networks:
      - web
      - stack_network

  db:
    image: postgres:latest                    # some older guides suggest mariadb of msql, pretix only works with postgresql since April 2023!
    restart: always
    environment:
      - POSTGRES_DB=pretix
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=
#      - POSTGRES_HOST_AUTH_METHOD=trust      # this line is not recommended and should be commented, however sometimes postgresql wont start and this can fix that.. use at your own risk
    ports:
      - "5432:5432"
    volumes:
      - /mnt/docker/pretix/postgresql:/var/lib/postgresql/data
    networks:
      - stack_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stack_network

networks: 
  web:
    external: true
  stack_network:
    external: false
